title = "TOML Example"

[kafka-input]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]



[output]
    [output.email]
    enabled = true

    ip = "10.0.0.1"
    dc = "eqdc10"

    [output.kafka]
    enabled = true

    ip = "10.0.0.1"
    dc = "eqdc10"


    [output.es]
    enabled = true

    ip = "10.0.0.1"
    dc = "eqdc10"

    [output.json]
    enabled = true














